# Generated by Django 4.1.3 on 2023-01-30 14:09

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Denied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client_id', models.CharField(max_length=10)),
                ('Denied_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Koclient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_type', models.CharField(choices=[('Client', 'Client'), ('Supplier', 'Supplier'), ('Bank', 'Bank')], default='Client', max_length=20)),
                ('Address', models.CharField(max_length=100)),
                ('Client_id', models.CharField(max_length=10)),
                ('Client_Status', models.CharField(choices=[('GOOD', 'GOOD'), ('BAD', 'BAD')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Kosupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_type', models.CharField(choices=[('Client', 'Client'), ('Supplier', 'Supplier'), ('Bank', 'Bank')], default='Supplier', max_length=20)),
                ('Address', models.CharField(max_length=100)),
                ('Supplier_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Kouser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('Phone', models.BigIntegerField(blank=True, null=True)),
                ('Is_bank', models.BooleanField(default=False)),
                ('Is_client', models.BooleanField(default=False)),
                ('Is_supplier', models.BooleanField(default=False)),
                ('DoB', models.DateField(blank=True, null=True)),
                ('Gender', models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHERS', 'OTHERS')], max_length=50, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Verified_Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Supplier_code', models.CharField(max_length=10)),
                ('Invoice_number', models.CharField(max_length=100)),
                ('Invoice_request', models.DateField(default=django.utils.timezone.now)),
                ('Invoice_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('Currency', models.CharField(default='INR', max_length=50)),
                ('Requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KOKO_bank_app.koclient')),
                ('Verified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KOKO_bank_app.kosupplier')),
            ],
        ),
        migrations.CreateModel(
            name='Requested_Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defa', models.CharField(default='defa', max_length=5)),
                ('Supplier_code', models.CharField(max_length=10)),
                ('Invoice_number', models.CharField(max_length=100)),
                ('Invoice_request', models.DateField(default=django.utils.timezone.now)),
                ('Invoice_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('Currency', models.CharField(default='INR', max_length=50)),
                ('Requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KOKO_bank_app.koclient')),
            ],
        ),
        migrations.AddField(
            model_name='kosupplier',
            name='Username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='koclient',
            name='Username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Approved_Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Supplier_code', models.CharField(max_length=10)),
                ('Invoice_number', models.CharField(max_length=100)),
                ('Invoice_request', models.DateField(default=django.utils.timezone.now)),
                ('Invoice_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('Currency', models.CharField(default='INR', max_length=50)),
                ('Approved_by', models.CharField(max_length=100)),
                ('Loan_id', models.CharField(blank=True, max_length=100, null=True)),
                ('Requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KOKO_bank_app.koclient')),
            ],
        ),
    ]
