# Generated by Django 4.1.3 on 2023-01-30 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KOKO_bank_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approved_invoice',
            old_name='Invoice_request',
            new_name='Invoice_date',
        ),
    ]
