# Generated by Django 4.1.3 on 2023-01-30 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KOKO_bank_app', '0003_remove_approved_invoice_loan_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requested_invoice',
            old_name='Invoice_request',
            new_name='Invoice_date',
        ),
        migrations.RenameField(
            model_name='verified_invoice',
            old_name='Invoice_request',
            new_name='Invoice_date',
        ),
    ]
