# Generated by Django 4.1.3 on 2023-01-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KOKO_bank_app', '0004_rename_invoice_request_requested_invoice_invoice_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approved_invoice',
            name='Requested_by',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='requested_invoice',
            name='Requested_by',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='verified_invoice',
            name='Requested_by',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='verified_invoice',
            name='Verified_by',
            field=models.CharField(max_length=50),
        ),
    ]
