# Generated by Django 4.1.3 on 2023-01-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KOKO_bank_app', '0005_alter_approved_invoice_requested_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denied',
            name='Client_id',
        ),
        migrations.AddField(
            model_name='denied',
            name='Invoice_number',
            field=models.CharField(default=22, max_length=100),
            preserve_default=False,
        ),
    ]
